name: Sync All Forks

on:
  schedule:
    - cron: '0 */12 * * *'  # Runs every 12 hours
  workflow_dispatch:  # Allows manual triggering
    inputs:
      specific_repo:
        description: 'Specific repository to sync (leave empty for all)'
        required: false
        type: string

jobs:
  sync-forks:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup GitHub CLI
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
      - name: Get list of forks and sync them
        env:
          GITHUB_TOKEN: ${{ secrets.SYNC_TOKEN }}  # Use your PAT here
          SPECIFIC_REPO: ${{ github.event.inputs.specific_repo }}
        run: |
          # Authenticate with GitHub CLI using the token
          echo "$GITHUB_TOKEN" | gh auth login --with-token
          
          # Get list of your forks
          if [ -z "$SPECIFIC_REPO" ]; then
            echo "Fetching all fork repositories..."
            FORKS=$(gh repo list --fork --json name -q '.[].name')
          else
            echo "Using specified repository: $SPECIFIC_REPO"
            FORKS="$SPECIFIC_REPO"
          fi
          
          echo "Found forks: $FORKS"
          
          if [ -z "$FORKS" ]; then
            echo "No forks found. Please check your GitHub account or token permissions."
            exit 0
          fi
          
          # Process each fork
          for repo in $FORKS; do
            echo "Processing $repo..."
            
            # Create temporary directory
            TEMP_DIR=$(mktemp -d)
            cd $TEMP_DIR
            
            # Clone the fork
            gh repo clone "${{ github.repository_owner }}/$repo" || { echo "Failed to clone $repo"; continue; }
            cd "$repo"
            
            # Get upstream URL
            UPSTREAM_URL=$(gh api "repos/${{ github.repository_owner }}/$repo" --jq '.parent.clone_url')
            
            if [ -n "$UPSTREAM_URL" ]; then
              echo "Syncing $repo with upstream $UPSTREAM_URL"
              
              # Add upstream and sync
              git remote add upstream "$UPSTREAM_URL"
              git fetch upstream
              DEFAULT_BRANCH=$(git symbolic-ref --short HEAD || echo "main")
              echo "Default branch is $DEFAULT_BRANCH"
              
              UPSTREAM_DEFAULT=$(git ls-remote --symref upstream HEAD | grep -oP 'refs/heads/\K[^\s]+' || echo "main")
              echo "Upstream default branch is $UPSTREAM_DEFAULT"
              
              git merge "upstream/$UPSTREAM_DEFAULT" -m "Sync with upstream"
              git push origin $DEFAULT_BRANCH
              
              echo "Successfully synced $repo"
            else
              echo "Could not find upstream for $repo"
            fi
            
            # Cleanup
            cd ../../
            rm -rf "$TEMP_DIR"
          done
